const D=window.CREATOR_COMMERCE_DEMO,SKU=D.sku,CAMP=D.campaign;
const creators=D.creators.filter(x=>['accepted','campaign'].includes(x.outreach.status));
const $=id=>document.getElementById(id),money=n=>'R$ '+Number(n).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
const statePt={requested:'Solicitada',review:'Em análise',approved:'Aprovada',shipped:'Enviada',delivered:'Entregue',content_due:'Aguardando conteúdo',posted:'Publicada',expired:'Expirada',pending:'Pendente'};
$('campaignName').textContent=CAMP.name;$('skuName').textContent=SKU.name;$('skuMeta').textContent=SKU.id+' · '+SKU.category;$('objective').textContent=CAMP.objective;$('dates').textContent=CAMP.start+' → '+CAMP.end;$('owner').textContent=CAMP.owner;$('campaignType').textContent=CAMP.type;$('samplePolicy').textContent=CAMP.samplePolicy;$('brief').textContent=CAMP.brief;$('sampleSla').textContent=CAMP.sampleSlaDays+' dias após entrega';$('exceptionDays').textContent=CAMP.sampleSlaDays;$('reminderRule').textContent=CAMP.sampleReminder;
const sampleCost=creators.reduce((a,x)=>a+(x.activation?.sampleCost||0),0),ship=creators.reduce((a,x)=>a+(x.activation?.shippingCost||0),0),rev=creators.reduce((a,x)=>a+(x.activation?.revenue||0),0),spent=sampleCost+ship;
$('budget').textContent=money(CAMP.budget);$('budgetUsage').textContent=money(spent)+' gasto · '+money(CAMP.budget-spent)+' restante';$('budgetBar').style.width=Math.min(100,spent/CAMP.budget*100)+'%';
const funnel=[['Contatado',6],['Respondeu',4],['Aceitou',2],['Amostra',2],['Publicou',1],['Converteu',1]];
$('funnel').innerHTML=funnel.map((x,i)=>"<div class='step "+(i===2||i===4?'warn':'')+"'><small>"+x[0]+"</small><b>"+x[1]+"</b><div class='sub'>"+(i?Math.round(x[1]/funnel[i-1][1]*100)+'% da etapa anterior':'base')+"</div></div>").join('');
$('bottleneck').textContent=CAMP.bottleneck;$('bottleneckDetail').textContent='Próxima ação recomendada: FOLLOW_UP_SAMPLE · responsável Bruno';
function stage(x){return x.activation?.stage==='posted'?['Publicado','green']:x.activation?.stage==='sample_approved'?['Amostra aprovada','blue']:['Aceitou','blue']}
function nextLabel(x){return x.activation?.nextAction==='FOLLOW_UP_SAMPLE'?'Enviar amostra':x.activation?.nextAction==='REPEAT_CREATOR'?'Repetir creator':'Revisar'}
function due(x){return x.activation?.nextAction==='FOLLOW_UP_SAMPLE'?x.activation.shipDue:(x.activation?.nextAction==='WAIT_FOR_CONTENT'?x.activation.contentDue:'—')}
function avatar(x){return x.n.split(' ').map(v=>v[0]).join('')}
let selected=new Set();
function renderRows(){ $('creatorRows').innerHTML=creators.map(x=>{const st=stage(x);return "<tr><td><input class='pick' data-id='"+x.id+"' type='checkbox' "+(selected.has(x.id)?'checked':'')+"></td><td><div class='creator'><span class='avatar'>"+avatar(x)+"</span><div><b>"+x.n+"</b><div class='sub'>"+x.h+"</div></div></div></td><td>"+x.cm+"%</td><td><span class='badge "+st[1]+"'>"+st[0]+"</span></td><td>"+x.activation.owner+"</td><td><b>"+nextLabel(x)+"</b><div class='actionCode'>"+x.activation.nextAction+"</div></td><td>"+due(x)+"</td><td>"+x.activation.orders+"</td><td>"+money(x.activation.revenue)+"</td><td><button class='btn rowAction' data-id='"+x.id+"'>"+nextLabel(x)+"</button></td></tr>"}).join('');
document.querySelectorAll('.pick').forEach(e=>e.onchange=()=>{const id=+e.dataset.id;e.checked?selected.add(id):selected.delete(id);bulk()});document.querySelectorAll('.rowAction').forEach(b=>b.onclick=()=>toast(nextLabel(creators.find(x=>x.id==b.dataset.id))+' — '+creators.find(x=>x.id==b.dataset.id).n));}
function bulk(){ $('selectedCount').textContent=selected.size+' selecionados'; const picked=creators.filter(x=>selected.has(x.id));$('bulkSample').disabled=!picked.some(x=>x.activation.nextAction==='FOLLOW_UP_SAMPLE');$('bulkReminder').disabled=!picked.some(x=>x.activation.nextAction==='WAIT_FOR_CONTENT'||x.activation.nextAction==='FOLLOW_UP_SAMPLE');$('bulkRepeat').disabled=!picked.some(x=>x.activation.nextAction==='REPEAT_CREATOR');}
renderRows();bulk();
$('selectAll').onchange=e=>{selected=e.target.checked?new Set(creators.map(x=>x.id)):new Set();renderRows();bulk()};
$('bulkSample').onclick=()=>toast('Amostras elegíveis preparadas para envio');$('bulkReminder').onclick=()=>toast('Lembretes preparados para creators elegíveis');$('bulkRepeat').onclick=()=>toast('Creators com resultado positivo preparados para repetição');
function pipeCard(x,label){return "<div class='pipeCard'><b>"+x.n+"</b><div class='sub'>"+label+"</div></div>"}
const acceptedStage=creators.filter(x=>x.activation.stage==='accepted');
const sampleStage=creators.filter(x=>['sample_approved','sample_shipped'].includes(x.activation.stage));
const contentStage=creators.filter(x=>x.activation.sample==='delivered'&&x.activation.content!=='posted');
const resultStage=creators.filter(x=>x.activation.content==='posted');
$('pipeAccepted').innerHTML=acceptedStage.map(x=>pipeCard(x,'Aceite confirmado')).join('')||'<div class="sub">—</div>';
$('pipeSample').innerHTML=sampleStage.map(x=>pipeCard(x,'Enviar até '+x.activation.shipDue)).join('')||'<div class="sub">—</div>';
$('pipeContent').innerHTML=contentStage.map(x=>pipeCard(x,'Aguardando conteúdo')).join('')||'<div class="sub">Nenhuma pendência</div>';
$('pipeResult').innerHTML=resultStage.map(x=>pipeCard(x,x.activation.orders+' pedidos · '+money(x.activation.revenue))).join('')||'<div class="sub">—</div>';
const states=['requested','review','approved','shipped','delivered','content_due','posted'];
$('sampleCards').innerHTML=creators.map(x=>{let idx=x.activation.content==='posted'?6:states.indexOf(x.activation.sample);if(idx<0)idx=2;return "<div class='sampleCard'><div class='row'><div><b>"+x.n+"</b><div class='sub'>1× "+SKU.name+"</div></div><span class='badge "+(x.activation.content==='posted'?'green':'blue')+"'>"+(x.activation.content==='posted'?'Publicada':'Em andamento')+"</span></div><div class='sampleFlow'>"+states.map((s,i)=>"<span class='"+(i<idx?'done':i===idx?'current':'')+"'>"+statePt[s]+"</span>").join('')+"</div><div class='sampleMeta'><span>Owner: <b>"+x.activation.owner+"</b></span><span>Prazo: <b>"+(x.activation.contentDue||x.activation.shipDue||'—')+"</b></span><span>Lembrete: <b>"+x.activation.reminder+"</b></span><span>Tracking: <b>"+(x.activation.tracking?.status||'—')+"</b></span><span>Código: <b>"+(x.activation.tracking?.code||'—')+"</b></span></div></div>"}).join('');
const commission=creators.reduce((a,x)=>a+(x.activation.revenue*x.cm/100),0),baseMargin=rev*SKU.baseMarginPct/100,margin=baseMargin-commission-sampleCost-ship;
$('campaignRevenue').textContent=money(rev);$('baseMarginValue').textContent=money(baseMargin);$('commissionCost').textContent='− '+money(commission);$('sampleCost').textContent='− '+money(sampleCost);$('shippingCost').textContent='− '+money(ship);$('campaignMargin').textContent=money(margin);$('campaignMarginPct').textContent=(rev?margin/rev*100:0).toFixed(1).replace('.',',')+'% da receita atribuída';$('salesRevenue').textContent=money(rev);
$('contentQueue').innerHTML=creators.map(x=>{const a=x.activation.contentAsset;if(!a)return "<div class='contentItem'><div class='thumb'>PEND.</div><div><b>"+x.n+"</b><div class='sub'>Nenhum conteúdo enviado · prazo após entrega da amostra</div></div><button class='btn' disabled title='Aguarde o envio do conteúdo'>Aprovar conteúdo</button></div>";return "<div class='contentItem'><div class='thumb'>"+a.type+"</div><div><b>"+a.title+"</b><div class='sub'>"+x.n+" · "+a.views.toLocaleString('pt-BR')+" visualizações · "+(a.status==='approved'?'Aprovado em '+a.approvedAt:'Aguardando aprovação')+"</div></div><div class='contentActions'>"+(a.status==='approved'?"<button class='btn' disabled title='Conteúdo já aprovado'>Aprovado</button>":"<button class='btn approve' data-id='"+x.id+"'>Aprovar conteúdo</button>")+"<button class='btn'>Abrir conteúdo</button></div></div>"}).join('');
document.querySelectorAll('.approve').forEach(b=>b.onclick=()=>toast('Conteúdo aprovado para '+creators.find(x=>x.id==b.dataset.id).n));
$('editCampaign').onclick=()=>toast('Editor de campanha — desenho v2');$('addCreator').onclick=()=>toast('Adicionar creator mostra somente creators aceitos no Outreach');$('viewPending').onclick=()=>toast('Lucas: enviar amostra até 09/10');$('openEconomics').onclick=()=>location.href='../unit-economics/index.html';$('navSku').onclick=()=>location.href='../sku-opportunity/index.html';$('navShortlist').onclick=()=>location.href='../creator-shortlist/index.html';$('navOutreach').onclick=()=>location.href='../outreach/index.html';$('navEconomics').onclick=()=>location.href='../unit-economics/index.html';
function toast(t){$('toast').textContent=t;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',1600)}

// Visual automation status for design review
const auto=document.createElement('div');auto.className='automationNote';auto.innerHTML="<b>Automação de follow-up ativa</b><span>Próxima checagem: Lucas · 09/10 às 09:00</span><small>Se entregue e sem publicação após "+CAMP.sampleSlaDays+" dias: WAIT_FOR_CONTENT + lembrete automático.</small>";document.querySelector('.pipelineWrap').appendChild(auto);