const D=window.CREATOR_COMMERCE_DEMO, SKU=D.sku, CAMP=D.campaign;
const creators=D.creators.filter(x=>['accepted','campaign'].includes(x.outreach.status));
const $=id=>document.getElementById(id), money=n=>'R$ '+Number(n).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
$('campaignName').textContent=CAMP.name;$('skuName').textContent=SKU.name;$('skuMeta').textContent=SKU.id+' · '+SKU.category;$('objective').textContent=CAMP.objective;$('dates').textContent=CAMP.start+' → '+CAMP.end;$('owner').textContent=CAMP.owner;$('budget').textContent=money(CAMP.budget);$('campaignType').textContent=CAMP.type;$('samplePolicy').textContent=CAMP.samplePolicy;$('brief').textContent=CAMP.brief;$('bottleneck').textContent=CAMP.bottleneck;
const funnel=[['Contatado',6],['Respondeu',4],['Aceitou',2],['Amostra',2],['Publicou',1],['Vendeu',1],['Converteu',1]];
$('funnel').innerHTML=funnel.map((x,i)=>"<div class='step "+(i===3?'warn':'')+"'><small>"+x[0]+"</small><b>"+x[1]+"</b><div class='sub'>"+(i?Math.round(x[1]/funnel[i-1][1]*100)+'% da etapa anterior':'base')+"</div></div>").join('');
function stage(x){const s=x.activation?.stage;return s==='posted'?['Publicado','green']:s==='sample_approved'?['Amostra aprovada','blue']:['Aceitou','blue']}
$('creatorRows').innerHTML=creators.map(x=>{const st=stage(x);return "<tr><td><div class='creator'><span class='avatar'>"+x.n.split(' ').map(v=>v[0]).join('')+"</span><div><b>"+x.n+"</b><div class='sub'>"+x.h+"</div></div></div></td><td>"+x.cm+"%</td><td><span class='badge "+st[1]+"'>"+st[0]+"</span></td><td>"+(x.activation?.sample||'—')+"</td><td>"+(x.activation?.content||'—')+"</td><td>"+(x.activation?.orders||0)+"</td><td>"+money(x.activation?.revenue||0)+"</td><td><button class='btn action' data-id='"+x.id+"'>Ver</button></td></tr>"}).join('');
const states=['requested','review','approved','shipped','delivered','content_due','posted'];
$('sampleCards').innerHTML=creators.map(x=>{const current=x.activation?.sample==='delivered'?'posted':x.activation?.sample||'approved';let idx=states.indexOf(current);if(x.activation?.content==='posted')idx=6;return "<div class='sampleCard'><div class='row'><div><b>"+x.n+"</b><div class='sub'>1× "+SKU.name+"</div></div><span class='badge "+(x.activation?.content==='posted'?'green':'blue')+"'>"+(x.activation?.content==='posted'?'Publicado':'Em andamento')+"</span></div><div class='sampleFlow'>"+states.map((s,i)=>"<span class='"+(i<idx?'done':i===idx?'current':'')+"'>"+s+"</span>").join('')+"</div>"+(x.activation?.sample==='delivered'&&x.activation?.content!=='posted'?"<div class='sub red'>Recebeu amostra e ainda não publicou</div>":"")+"</div>"}).join('');
const sampleCost=creators.reduce((a,x)=>a+(x.activation?.sampleCost||0),0),ship=creators.reduce((a,x)=>a+(x.activation?.shippingCost||0),0),rev=creators.reduce((a,x)=>a+(x.activation?.revenue||0),0);
$('sampleCost').textContent=money(sampleCost);$('shippingCost').textContent=money(ship);$('campaignRevenue').textContent=money(rev);
document.querySelectorAll('.action').forEach(b=>b.onclick=()=>{const x=creators.find(v=>v.id==b.dataset.id);toast(x.n+': '+stage(x)[0])});
$('openEconomics').onclick=()=>location.href='../unit-economics/index.html';$('navSku').onclick=()=>location.href='../sku-opportunity/index.html';$('navShortlist').onclick=()=>location.href='../creator-shortlist/index.html';$('navOutreach').onclick=()=>location.href='../outreach/index.html';$('navEconomics').onclick=()=>location.href='../unit-economics/index.html';
function toast(t){$('toast').textContent=t;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',1500)}
